package com.ypg.neville.feature.transformation.domain

object TransformationCatalog {
    val examples = listOf(
        TransformationExample("Responder mejor a una crítica", "Reacción defensiva", "recibo una crítica o una corrección sobre mi trabajo", "no valoran mi esfuerzo y tengo que defenderme", "tensión en la mandíbula, vergüenza e irritación", "interrumpo, justifico mis decisiones o respondo con dureza", "la conversación se vuelve tensa y pierdo información que podría ayudarme", "respiraré lentamente, escucharé hasta el final y haré una pregunta antes de responder", "incomodidad y vulnerabilidad", "escucha con serenidad y utiliza el feedback para aprender"),
        TransformationExample("Comenzar una tarea difícil", "Procrastinación por incomodidad", "tengo que comenzar una tarea importante, incierta o exigente", "necesito sentirme preparado y tener más tiempo para hacerlo bien", "pesadez, inquietud y resistencia", "abro el correo, ordeno cosas menores o pospongo el inicio", "acumulo presión, reduzco la calidad del trabajo y refuerzo la evitación", "cerraré las distracciones y trabajaré diez minutos en el primer paso concreto", "pereza, duda y falta de motivación", "empieza con claridad aunque todavía no se sienta preparado"),
        TransformationExample("Reducir la revisión del teléfono", "Revisión compulsiva del teléfono", "aparece una pausa, aburrimiento o una notificación", "solo miraré un momento por si hay algo importante", "inquietud en las manos y deseo de estimulación", "desbloqueo el teléfono y salto entre aplicaciones sin una intención definida", "pierdo atención, alargo las pausas y termino más disperso", "dejaré el teléfono fuera de alcance, haré tres respiraciones y volveré a la actividad elegida", "aburrimiento y curiosidad", "protege deliberadamente su atención"),
        TransformationExample("Regular la comida por estrés", "Comer impulsivamente bajo estrés", "termino una situación exigente o siento sobrecarga emocional", "necesito comer algo ahora para sentirme mejor", "vacío en el abdomen, tensión y urgencia", "como rápidamente sin comprobar si tengo hambre física", "obtengo alivio breve y después siento pesadez, culpa y menor confianza", "beberé agua, caminaré cinco minutos y comprobaré de nuevo mi hambre antes de decidir", "ansiedad y deseo", "atiende sus necesidades sin reaccionar automáticamente"),
        TransformationExample("Afrontar una conversación incómoda", "Evitación de conversaciones", "necesito expresar un límite, desacuerdo o petición importante", "si lo digo crearé un conflicto o decepcionaré a la otra persona", "presión en el pecho, miedo y anticipación", "pospongo la conversación, cedo o comunico de forma indirecta", "acumulo resentimiento y el problema continúa sin una solución clara", "prepararé una petición concreta y propondré un momento para hablar con calma", "miedo al conflicto y posible desaprobación", "comunica sus límites con honestidad y respeto"),
        TransformationExample("Mantener una rutina sin resultados inmediatos", "Abandono prematuro", "no observo resultados rápidos o pierdo un día de mi rutina", "esto no está funcionando y ya he estropeado el progreso", "desánimo, impaciencia y frustración", "abandono varios días o busco un plan nuevo", "impido la continuidad necesaria y refuerzo la idea de que no soy constante", "realizaré hoy la versión mínima y revisaré el proceso al final de la semana", "desánimo e incertidumbre", "prioriza la constancia y vuelve al proceso después de un desliz")
    )

    val days = listOf(
        day(1, "Contrato de transformación", 1, "Definir con precisión qué cambiarás y por qué.", "Escribe tu contrato. Durante 21 días no necesitas demostrar que ya has cambiado: observa, practica y recopila evidencias mediante tus acciones.", listOf("¿Desde cuándo observas el patrón y en qué situaciones aparece?", "¿Qué costes produce y qué beneficio oculto proporciona?", "¿Qué ocurrirá dentro de un año si no cambia?", "¿Qué posibilidades aparecerán al responder de otra forma?"), "Comparte el compromiso con alguien de confianza o déjalo visible.", "Un patrón puede aliviar, proteger o dar control a corto plazo. Reconocer esa recompensa permite cambiarlo."),
        day(2, "Mapa de desencadenantes", 1, "Identificar qué inicia el patrón.", "Clasifica tus desencadenantes en externos, internos, cognitivos, emocionales y contextuales.", listOf("Personas, palabras, lugares, horarios o dispositivos.", "Cansancio, hambre, dolor, aburrimiento, inseguridad o soledad.", "Recuerdos, comparaciones, expectativas o interpretaciones."), "Registra tres señales tempranas, aunque el patrón no llegue a completarse."),
        day(3, "Lenguaje del antiguo yo", 1, "Detectar las frases mentales que sostienen la conducta.", "Distingue hechos de interpretaciones y crea una alternativa precisa, creíble y operativa.", listOf("¿Es un hecho o una interpretación?", "¿Qué emoción produce?", "¿Qué conducta favorece?", "¿Qué alternativa sería más precisa?"), "Cuando aparezca una frase automática, di: «Estoy teniendo el pensamiento de que…».", "Observar un pensamiento reduce la identificación con su contenido."),
        day(4, "Memoria corporal", 1, "Reconocer cómo comienza el patrón en el cuerpo.", "Recuerda tres episodios y localiza el primer cambio corporal, la tensión, la respiración, la postura, la temperatura y el movimiento.", listOf("¿Cuál es la primera señal física?", "¿Dónde aparece la máxima tensión?", "Completa: «Mi patrón comienza con…»."), "Haz cinco exploraciones corporales breves a lo largo del día.", "Practica la detección antes de estar alterado."),
        day(5, "Cadena de consecuencias", 1, "Observar el coste completo del comportamiento.", "Traza la cadena antigua y después una alternativa: desencadenante → pensamiento → emoción → impulso → conducta → consecuencias → identidad reforzada.", listOf("¿Qué alivio inmediato ofrece la conducta antigua?", "¿Qué coste aparece a medio plazo?", "¿Cómo sería la cadena con la respuesta alternativa?"), "Antes de actuar, imagina durante diez segundos las consecuencias de segundo orden."),
        day(6, "Diseño del entorno", 1, "Reducir la dependencia de la fuerza de voluntad.", "Clasifica el entorno según favorezca el patrón antiguo, el nuevo o sea neutral. Realiza tres cambios concretos.", listOf("¿Qué señal hace demasiado fácil la conducta antigua?", "¿Qué barrera física o tecnológica puedes añadir?", "¿Qué puedes dejar preparado para facilitar la conducta nueva?"), "Aplica hoy una barrera contra el patrón antiguo.", "Haz más difícil la conducta antigua y más sencilla la nueva."),
        day(7, "Primera revisión", 1, "Convertir las observaciones en una hipótesis de trabajo.", "Revisa desencadenante, señal corporal, pensamiento, emoción evitada, recompensa, vulnerabilidades y eficacia del entorno.", listOf("¿Cuál fue el desencadenante más frecuente?", "¿En qué momento podías haber intervenido antes?", "¿Cuántas pausas y respuestas alternativas realizaste?"), "Resume tu hipótesis del patrón en tres líneas.", "Ver con más claridad el automatismo ya es progreso."),
        day(8, "Construcción de la pausa", 2, "Insertar espacio entre impulso y acción.", "Practica P.A.R.A. cinco veces en calma: percibe la señal, aplaza, regula y actúa según el protocolo.", listOf("¿Qué palabra interna señalará la pausa?", "¿Qué parte del cuerpo relajarás primero?", "¿Cuál es la conducta alternativa exacta?"), "Usa una señal física de pausa al menos una vez.", "No esperes a estar activado para entrenar la pausa."),
        day(9, "Tolerancia a la emoción", 2, "Sentir una emoción incómoda sin obedecerla.", "Durante 90 segundos observa ubicación, tamaño, intensidad, temperatura, presión y movimiento sin elaborar la historia mental.", listOf("¿Dónde está la emoción?", "¿Cómo cambia durante 90 segundos?", "¿Qué impulso puedes dejar pasar sin ejecutarlo?"), "Permanece deliberadamente con una incomodidad leve sin escapar.", "La emoción puede estar presente sin convertirse en conducta."),
        day(10, "Pensamiento operativo", 2, "Sustituir interpretaciones absolutas por instrucciones útiles.", "Crea una respuesta creíble, precisa y que favorezca la conducta elegida.", listOf("¿Qué parte de tu pensamiento automático es absoluta?", "¿Qué sí controlas?", "¿Qué frase te devuelve al proceso?"), "Coloca una frase operativa en un lugar visible.", "No necesitas creer una afirmación grandiosa; necesitas una instrucción practicable."),
        day(11, "Conducta incompatible", 2, "Elegir una acción que dificulte continuar el patrón antiguo.", "Completa: «Cuando detecte…, realizaré inmediatamente… durante… minutos».", listOf("¿Qué acción no puede coexistir fácilmente con tu patrón?", "¿Cuánto tiempo necesitas mantenerla?", "¿Cómo la iniciarás sin negociar contigo?"), "Ejecuta la conducta incompatible ante un desencadenante leve."),
        day(12, "Exposición gradual", 2, "Practicar ante una versión controlada del desencadenante.", "Crea una escala de intensidad del 1 al 10 y practica hoy con una situación de nivel 3 o 4.", listOf("¿Qué intensidad anticipabas y cuál fue la real?", "¿Qué respuesta utilizaste?", "¿Cuánto tardaste en recuperarte?"), "Realiza una exposición manejable y registra el proceso.", "El objetivo no es estar totalmente tranquilo, sino ejecutar el protocolo."),
        day(13, "R.E.P.A.R.A. un desliz", 2, "Evitar que un error se convierta en una cadena.", "Reconoce, evita el juicio global, para la cadena, analiza, repara y ajusta.", listOf("¿Cuál es tu desliz más probable?", "¿Cómo detendrás las decisiones posteriores?", "¿Qué puedes reparar?"), "Escribe anticipadamente tu plan de reparación.", "Una conducta que quieres modificar no define tu identidad."),
        day(14, "Segunda revisión", 2, "Comprobar si la respuesta automática pierde velocidad.", "Visualiza un episodio leve, uno moderado y uno intenso. En cada uno practica señal, pausa, emoción, frase operativa y respuesta alternativa.", listOf("¿Detectas antes las señales?", "¿Qué regulación funciona mejor?", "¿Estás practicando o solo reflexionando?"), "Ensaya los tres niveles durante cinco minutos.", "Una pequeña separación entre impulso y respuesta ya es éxito."),
        day(15, "Identidad basada en conducta", 3, "Definir quién quieres ser mediante acciones concretas.", "Completa «Estoy entrenando para convertirme en una persona que…» y tradúcelo en cinco conductas observables.", listOf("¿Qué identidad de proceso quieres entrenar?", "¿Qué cinco acciones la demuestran?", "¿Cuál puedes realizar hoy?"), "Produce una evidencia pequeña de esa identidad.", "Prefiere identidades como paciente, íntegro, constante o responsable frente a resultados externos."),
        day(16, "Acumulación de evidencias", 3, "Reforzar la identidad mediante pruebas reales.", "Registra evidencias conductuales: pausas, límites respetados, acciones iniciadas, escucha, tolerancia o recuperación.", listOf("¿Qué hiciste aunque apareció incomodidad?", "¿Qué límite respetaste?", "¿Cómo regresaste al proceso tras un error?"), "Busca tres evidencias pequeñas, no una demostración heroica.", "Registra lo que hiciste, no solo cómo te sentiste."),
        day(17, "Estrés controlado", 3, "Mantener la respuesta nueva con presión moderada.", "Antes de una dificultad manejable, prepara desencadenante, señal, pensamiento, pausa, conducta alternativa y criterio de detención.", listOf("¿Qué desencadenante esperas?", "¿Cuál será tu criterio para detenerte?", "Puntúa por separado resultado externo y calidad del proceso."), "Realiza una prueba moderada y evalúa la ejecución.", "Un mal resultado externo puede coexistir con un proceso excelente."),
        day(18, "Entorno social y límites", 3, "Alinear relaciones y entorno con la nueva conducta.", "Identifica apoyos, dinámicas que refuerzan el patrón, conversaciones evitadas y límites necesarios.", listOf("¿Qué persona puede ofrecer apoyo específico?", "¿Qué dinámica necesitas abandonar?", "¿Qué petición clara necesitas hacer?"), "Comunica un límite o una petición concreta.", "«Cuando ocurre…, me resulta difícil… A partir de ahora voy a… Te pido que…»"),
        day(19, "Visualización de obstáculos", 3, "Ensayar dificultades, no solo el éxito.", "Divide el ensayo en deseo, resultado, obstáculo interno y plan de respuesta.", listOf("¿Qué identidad construyes?", "¿Qué mejorará al actuar así?", "¿Qué pensamiento, emoción o impulso puede detenerte?", "¿Qué harás exactamente cuando aparezca?"), "Ensaya el obstáculo tres veces con la respuesta nueva."),
        day(20, "Simulación integral", 3, "Ejecutar el protocolo completo como una situación real.", "Simula contexto, señal, pensamiento, emoción, impulso, pausa, regulación, frase, conducta, posible desliz, reparación y cierre.", listOf("Incluye dudas y una emoción que no desaparece.", "Incluye un resultado incierto.", "Incluye el deseo de volver al patrón y la reparación."), "Realiza una versión realista o una acción que te acerque a ella.", "Mantén el proceso aunque la experiencia sea imperfecta."),
        day(21, "Evaluación y consolidación", 3, "Medir el cambio y convertirlo en un sistema sostenible.", "Compara frecuencia, intensidad, detección, pausas, respuestas alternativas, recuperación, consecuencias y confianza entre el inicio y hoy.", listOf("¿Qué descubriste y qué respuesta funciona mejor?", "¿Qué evidencia demuestra el cambio?", "¿Qué parte necesita más entrenamiento?", "¿Qué conducta mantendrás durante 30 días?"), "Conserva visible el protocolo y agenda cuatro revisiones semanales.", "La nueva identidad se establece al acumular experiencias de respuesta diferente ante el mismo desencadenante.")
    )

    val morningRoutine = listOf(
        TransformationRoutineStep("Regulación fisiológica", 3, "Inhala 4 segundos, exhala 6. Relaja mandíbula, hombros y manos."),
        TransformationRoutineStep("Observación corporal", 4, "Recorre rostro, cuello, pecho, abdomen, espalda, brazos y piernas."),
        TransformationRoutineStep("Reconocer el patrón", 5, "Observa señal, pensamiento, emoción e impulso sin convertirlos en identidad."),
        TransformationRoutineStep("Interrupción y ensayo", 7, "Imagina el obstáculo, reconoce la urgencia y ejecuta tu respuesta alternativa."),
        TransformationRoutineStep("Compromiso del día", 2, "Define una acción observable que demostrará hoy tu nueva identidad.")
    )

    val minimumRoutine = listOf(
        TransformationRoutineStep("Respiración lenta", 2, "Reduce la activación con una exhalación más larga."),
        TransformationRoutineStep("Observación corporal", 2, "Localiza tensión e inquietud sin intentar eliminarlas."),
        TransformationRoutineStep("Reconocer el patrón", 2, "Nombra el patrón y su impulso."),
        TransformationRoutineStep("Ensayo mental", 2, "Practica la pausa y la respuesta alternativa."),
        TransformationRoutineStep("Acción del día", 2, "Escribe una conducta observable.")
    )

    private fun day(number: Int, title: String, phase: Int, objective: String, exercise: String, prompts: List<String>, action: String, principle: String? = null) =
        TransformationDayPlan(number, title, when (phase) { 1 -> "Fase I · Observar y cartografiar"; 2 -> "Fase II · Interrumpir y sustituir"; else -> "Fase III · Construir y consolidar" }, objective, exercise, prompts, action, principle)
}
